### ISSUE TITLE
Rebuild with Python 3.11 support to fix "fatal error: longintrepr.h: No such file or directory"

### ISSUE THREAD

**Issue by sbraz** [universal-ctags/python-ctags3#16]
Hi @jonashaag,
The current PyPI tarball doesn't work with Python 3.11:
```
x86_64-pc-linux-gnu-gcc -Wsign-compare -DNDEBUG -O2 -pipe -march=native -fPIC -Isrc/include -I/usr/include/python3.11 -c src/_readtags.c -o build/temp.linux-x86_64-cpython-311/src/_readtags.o
src/_readtags.c:196:12: fatal error: longintrepr.h: No such file or directory
  196 |   #include "longintrepr.h"
      |            ^~~~~~~~~~~~~~~
```

Regenerating `_readtags.c` with a recent Cython version works, can you please do it and upload a new release on PyPI?

**Comment by jonashaag** [comment]
Done!

**Comment by sbraz** [comment]
Hi @jonashaag, can you push a release to PyPI with this change or should I apply the patch to the Gentoo package?

**Comment by sbraz** [comment]
I ended up regenerating the extension with Cython: https://github.com/gentoo/gentoo/commit/4338694a9420cb9bd1d05a160127ab90b579f589. Apparently it is now Gentoo's policy: https://projects.gentoo.org/python/guide/distutils.html#packages-using-cython.
